services:
  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://mongo:27017
      MONGO_DB: library_db
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongodata: