volumes:
  mongo_data:

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: books
    volumes:
      - mongo_data:/var/lib/mongo/data
    ports:
      - "27017:27017"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mongosh", "-u", "mongo_admin", "-p", "password", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://mongo_admin:password@mongodb:27017/?authSource=admin
      mongodb: books
    networks:
      - app_network
    depends_on:
      mongodb:
        condition: service_healthy

networks:
  app_network:
    driver: bridge
